/*
 DeckLinkController talks to the DeckLink SDK (16.0): lists the devices, configures
 them (input connection, profile), starts and stops a capture stream in the mode and
 pixel format you choose, and hands the frames to the app through a triple buffer.
 Format detection is only used to report what is arriving: the capture never
 switches by itself, a mismatch gives a warning with the details of the signal.

 Frames are not copied: the SDK frame itself is kept (reference counted) until the
 app has moved on, and the app reads its memory directly (IDeckLinkVideoBuffer).
 Colour conversion only happens when the app asks for it (GPU shader or CPU).

 Platform differences of the SDK are kept in here:
   macOS   CoreFoundation strings, the API is loaded by DeckLinkAPIDispatch.cpp
   Linux   C strings, the API is loaded by DeckLinkAPIDispatch.cpp
   Windows COM: BSTR strings, BOOL flags, objects created with CoCreateInstance
           (DeckLinkAPI.h / DeckLinkAPI_i.c generated by scripts/generate_windows_headers.bat)
 */

#pragma once

#include "ofMain.h"

#include "DeckLinkAPI.h"
#include "TripleBuffer.h"

#include <atomic>
#include <functional>
#include <mutex>

#ifndef STDMETHODCALLTYPE
#define STDMETHODCALLTYPE
#endif

#ifdef _WIN32
typedef BOOL DLBool;
typedef LONGLONG DLInt;
#else
typedef bool DLBool;
typedef int64_t DLInt;
#endif

// What a device is and can do (from IDeckLinkProfileAttributes)
struct DeckLinkDeviceInfo {
	int index = -1;
	std::string displayName;   // e.g. "UltraStudio 4K Mini"
	std::string modelName;
	int64_t persistentId = 0;  // stable across reboots and ports (0 if the device doesn't report one)
	int subDeviceIndex = 0;    // input number on multi-input cards
	int numSubDevices = 1;
	std::string interfaceName; // "PCIe", "USB", "Thunderbolt"
	bool canCapture = false;
	bool canPlayback = false;
	bool supportsFormatDetection = false;
	std::vector<BMDVideoConnection> inputConnections; // SDI, HDMI, optical SDI...
};

// A profile of a multi-input card (e.g. DeckLink Duo 2: 4 half duplex inputs or 2 full duplex)
struct DeckLinkProfileInfo {
	BMDProfileID id = 0;
	std::string name;
	bool active = false;
};

// What is actually arriving at the input (format detection), to compare with
// what the capture is set to.
struct DeckLinkSignalInfo {
	bool present = false;        // frames with a picture are arriving
	bool detected = false;       // the format below comes from format detection
	BMDDisplayMode displayMode = bmdModeUnknown;
	std::string modeName;        // e.g. "1080p25"
	int width = 0;
	int height = 0;
	float frameRate = 0;
	bool rgb = false;            // RGB 4:4:4, else YUV 4:2:2
	int bitDepth = 0;            // 8, 10 or 12 (0: unknown)
	std::string describe() const; // "1080p25 1920x1080, 10 bit YUV 4:2:2"
};

// One captured frame, as delivered by the device. `frame` is held (AddRef) by the
// controller; read its memory with DeckLinkController::readFrame().
struct DeckLinkRawFrame {
	IDeckLinkVideoInputFrame* frame = nullptr;
	int width = 0;
	int height = 0;
	int rowBytes = 0;
	BMDPixelFormat pixelFormat = bmdFormat8BitYUV; // 8BitYUV (2vuy), 10BitYUV (v210), 8BitARGB or 10BitRGB (r210)
	uint64_t number = 0;                           // frame counter since the capture started
};

class DeckLinkController : public IDeckLinkInputCallback {
private:
	std::vector<IDeckLink*> deviceList;
	IDeckLink* selectedDevice;
	IDeckLinkInput* deckLinkInput;
	std::vector<IDeckLinkDisplayMode*> modeList;

	bool supportFormatDetection;
	bool currentlyCapturing;
	int selectedIndex;
	bool comInitialized;
	BMDPixelFormat requestedPixelFormat;

	IDeckLinkVideoConversion* videoConverter;

	// What is coming in now; changes when the input format changes
	std::atomic<int> frameWidth, frameHeight;
	std::atomic<bool> signalPresent;
	std::atomic<uint32_t> currentDisplayMode;
	std::atomic<uint32_t> currentPixelFormat;
	std::atomic<uint64_t> framesArrived;
	std::atomic<uint64_t> framesSkipped;
	std::mutex timecodeMutex;
	std::string timecode;
	std::mutex signalMutex;
	DeckLinkSignalInfo signal;
	std::string signalWarning;
	void updateSignalWarning(); // with signalMutex locked

	void getAncillaryDataFromFrame(IDeckLinkVideoInputFrame* frame, BMDTimecodeFormat format, std::string& timecodeString, std::string& userBitsString);
	IDeckLinkDisplayMode* findMode(BMDDisplayMode mode);
	bool enableInput(BMDDisplayMode mode, BMDPixelFormat pixelFormat);
	void releaseDevices();
	void releaseFrames();

public:
	TripleBuffer<DeckLinkRawFrame> buffer;

	DeckLinkController();
	virtual ~DeckLinkController();

	bool init();

	int getDeviceCount();
	std::vector<std::string> getDeviceNameList();
	std::vector<DeckLinkDeviceInfo> getDeviceInfoList();

	bool selectDevice(int index);

	// Pixel format of the capture: bmdFormat8BitYUV (default), bmdFormat10BitYUV,
	// bmdFormat8BitARGB or bmdFormat10BitRGB. Set before startCapture. The capture
	// never changes it by itself: if the signal is different, getSignalWarning() says so.
	void setPixelFormat(BMDPixelFormat format) { requestedPixelFormat = format; }
	BMDPixelFormat getPixelFormat() const { return requestedPixelFormat; }

	// Input connection of the selected device (SDI, HDMI...). Can be changed while capturing.
	std::vector<BMDVideoConnection> getInputConnections();
	bool setInputConnection(BMDVideoConnection connection);
	BMDVideoConnection getInputConnection();

	// Profiles of a device (multi-input cards). Activating one may change the number of
	// devices: call init() / listDevices() again afterwards.
	std::vector<DeckLinkProfileInfo> getProfiles(int deviceIndex);
	bool setProfile(int deviceIndex, BMDProfileID profile);

	std::vector<std::string> getDisplayModeNames();
	bool isFormatDetectionEnabled();
	bool isCapturing();

	bool startCaptureWithMode(BMDDisplayMode videoMode);
	bool startCaptureWithIndex(int videoModeIndex);
	void stopCapture();

	// IUnknown (the controller lives as long as the capture, no reference counting)
	virtual HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, LPVOID* ppv) { return E_NOINTERFACE; }
	virtual ULONG STDMETHODCALLTYPE AddRef() { return 1; }
	virtual ULONG STDMETHODCALLTYPE Release() { return 1; }

	// IDeckLinkInputCallback
	virtual HRESULT STDMETHODCALLTYPE VideoInputFormatChanged(BMDVideoInputFormatChangedEvents notificationEvents, IDeckLinkDisplayMode* newDisplayMode, BMDDetectedVideoInputFormatFlags detectedSignalFlags);
	virtual HRESULT STDMETHODCALLTYPE VideoInputFrameArrived(IDeckLinkVideoInputFrame* videoFrame, IDeckLinkAudioInputPacket* audioPacket);

	// Looks the mode up in the modes the selected device reports, so every
	// mode the hardware supports works. framerate <= 0 picks the highest
	// progressive rate (interlaced only if there is no progressive mode).
	BMDDisplayMode getDisplayMode(int w, int h);
	BMDDisplayMode getDisplayMode(int w, int h, float framerate);
	bool getDisplayModeInfo(BMDDisplayMode mode, int& w, int& h, float& framerate, std::string& name);

	// Reads a frame's memory (SDK 14.3+: through IDeckLinkVideoBuffer).
	static bool readFrame(IDeckLinkVideoFrame* frame, const std::function<void(const unsigned char* bytes)>& reader);
	// Converts any captured frame to 8 bit RGBA pixels (the SDK's converter, CPU).
	bool convertToRGBA(IDeckLinkVideoFrame* frame, ofPixels& rgba);

	int getFrameWidth() { return frameWidth; }
	int getFrameHeight() { return frameHeight; }
	bool hasSignal() { return signalPresent; }
	BMDDisplayMode getCurrentDisplayMode() { return BMDDisplayMode(currentDisplayMode.load()); }
	BMDPixelFormat getCurrentPixelFormat() { return BMDPixelFormat(currentPixelFormat.load()); }
	uint64_t getFramesArrived() { return framesArrived; }
	uint64_t getFramesSkipped() { return framesSkipped; } // arrived but replaced before the app took them
	std::string getTimecode();
	// What is arriving at the input, and a warning when it doesn't match the capture
	// settings (empty when it matches).
	DeckLinkSignalInfo getSignal();
	std::string getSignalWarning();
	int getSelectedDeviceIndex() { return selectedIndex; }

	static std::string connectionName(BMDVideoConnection connection);
	static std::string profileName(BMDProfileID profile);
	static std::string pixelFormatName(BMDPixelFormat format);
	static bool isRGB(BMDPixelFormat format);
	static int bitDepth(BMDPixelFormat format);
};
